config/routes.rb
Rails.application.routes.draw do

  get 'posts/:id', to: 'posts#show'
  get 'posts', to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_tags
  has_many :tags, through: :post_tags
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
  	page = params[:page] || 1
  	page_offset = (page - 1) * 10
  	@posts = Post.order(written_at: :desc).offset(page_offset).limit(10)
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blarg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<div class="post">
  <h2><%= link_to_unless_current post.title, post_path(post) %></h2>
  <h3>Written on: <%= @post.written_at %></h3>

  <% = simple_format(@post.content) %>
</div>

app/views/posts/index.html.erb
<% link_to "Add New Post", posts_new_path %>

<div class="posts">
  <% @posts.each do |post| %>
    <%= render partial: "post", object: post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h2>New Post</h2>

<!--Title, Tags, Text-->

<%= form_tag('/posts', class: 'post-form') do %>
  <div>
    <%= label_tag(:title, "Title: ") %>
    <%= text_field_tag(:title, nil, size: 40) %>
  </div>

  <br/>

  <div>
    <%= label_tag(:title, "Tags: ") %>
    <%= text_field_tag(:title, nil, size: 40) %>
  </div>

  <br/>

  <div>
    <%= label_tag(:title, "Content: ") %>
  <br/>
    <%= text_area_tag(:content, nil, rows: 40, cols: 80) %>
  </div>
  
  <br/>
  <div><%= submit_tag 'Save' %></div>
  
  <br/>
  <div>
  <%= link_to "Back", :back %>
  </div>
<% end %>
  

app/views/posts/show.html.erb
<%= render partial: "posts", locals: { post: @post } %>

<%= render partial: "post", object: @post %>

<%= link_to "Posts Index", posts_path %>

app/views/posts/view.html.erb
<h1>Hello World!</h1>